name: Check build on Windows

on:
  push:
    branches:
      - master
      - dev
      - feature_crossplatform_compilation

env:
  CMAKE_GENERATOR: Ninja
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    name: Cmake build on Windows
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            git
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-msmpi
      - name: Put MSYS2_MinGW64 on PATH
        # there is not yet an environment variable for this path from msys2/setup-msys2
        run: echo "D:/a/_temp/msys64/mingw64/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: download MS-MPI setup (SDK is from MSYS2)
        run: curl -L -O https://github.com/microsoft/Microsoft-MPI/releases/download/v10.1.1/msmpisetup.exe

      - name: Install mpiexec.exe (-force needed to bypass GUI on headless)
        run: .\msmpisetup.exe -unattend -force

      - name: test that mpiexec.exe exists
        # can't use MSMPI_BIN as Actions doesn't update PATH from msmpisetup.exe
        run: Test-Path "C:\Program Files\Microsoft MPI\Bin\mpiexec.exe" -PathType leaf

      - name: put MSMPI_BIN on PATH (where mpiexec is)
        run: echo "C:\Program Files\Microsoft MPI\Bin\" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - uses: actions/checkout@v2
        name: Checkout source code

      - name: download submodules
        run: git submodule update --init --recursive

      - name: CMake configure
        run: cmake -B build

      - name: CMake build
        run: cmake --build build